### ISSUE TITLE
No output from checkpatch plugin on problems pane

### ISSUE THREAD

**Issue by maroueneboubakri** [idanpa/vscode-checkpatch#1]
Hi @idanpa ,

Thank you for making this plugin available for us.

After finishing the installation and invoking the plugin on a open C source file, no output seen on the editor (problems pane).

I got it working after disabling/enabling it several times.

Closing and opening again vscode causes the same issue again.

I'm not sure if there is a specific requirement to get it working.

Thanks
Maro

**Comment by idanpa** [comment]
Thank you @maroueneboubakri for submitting this issue. 

After some testing I couldn't recreate the problem but I fixed some bug that may have cause this issue (provideCodeActions was not implemented).
 
I've uploaded version 0.0.4, please update and let me know if this problem persists.

**Comment by maroueneboubakri** [comment]
Thank you @idanpa for your quick reaction. I close this thread.
