### ISSUE TITLE
.checkpatch.conf support

### ISSUE THREAD

**Issue by Izikd** [idanpa/vscode-checkpatch#4]
Hi,

Can you please add ".checkpatch.conf" support?

.checkpatch.conf is placed at the root directory of a project and checkpatch.pl detects it for various configurations.
Example: https://github.com/openil/u-boot/blob/master/.checkpatch.conf

Basically it requires the checkpatch.pl to be executed when CWD is the project directory.

**Comment by idanpa** [comment]
Nice to see you here @Izikd, fixed in 0.0.8.
